FROM python:3.11-slim

WORKDIR /mlops-project

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements_server1.txt .
RUN pip install --no-cache-dir -r requirements_server1.txt

COPY . .

ENV PYTHONUNBUFFERED=1

CMD ["python", "scripts/main.py", "all", "--model_name", "movie_predictor"]